name: Integration tests

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  integration-tests:
    name: Playwright tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install dependencies
      run: python -m pip install -U jupyterlab~=3.1 check-manifest

    - name: Install the extension
      run: |
        set -eux
        jlpm
        python -m pip install .

    - name: Launch JupyterLab
      run: |
        (jupyter lab --config jupyter_server_test_config.py > /tmp/jupyterlab_server.log 2>&1) &

    - name: Install browser
      run: |
        jlpm playwright install chromium

    - name: Wait for JupyterLab
      uses: ifaxity/wait-on-action@v1
      with:
        resource: http-get://localhost:8888/lab
        timeout: 360000

    - name: Execute integration tests
      run: |
        jlpm run playwright test ./ui-tests

    - name: Upload Playwright Test assets
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: {{ cookiecutter.python_name }}-playwright-test-assets
        path: |
          test-results

    - name: Upload Playwright Test report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: {{ cookiecutter.python_name }}-playwright-report
        path: |
          playwright-report

    - name: Stop JupyterLab
      if: always()
      run: |
        kill -s SIGTERM $(pgrep jupyter-lab)

    - name: Print JupyterLab logs
      if: always()
      run: |
        cat /tmp/jupyterlab_server.log
