name: Tests validation

on:
  push:
    branches: ["*.0"]
  pull_request:
    branches: "*"
  schedule:
    - cron: "0 0 * * *"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install dependencies
        run: python -m pip install -U cookiecutter check-manifest jupyterlab~=3.1

      - name: Create the extension
        run: |
          set -eux
          # Trick to use custom parameters
          python -m cookiecutter --no-input .
          
      - name: Test the extension
        working-directory: myextension
        run: |
          set -eux
          jlpm
          jlpm test

      - name: Install the extension
        working-directory: myextension
        run: |
          set -eux
          python -m pip install .

      - name: Launch JupyterLab
        working-directory: myextension
        run: |
          jupyter lab --config jupyter_server_test_config.py 2>&1 > /tmp/jupyterlab_server.log &

      - name: Install browser
        working-directory: myextension
        run: |
          jlpm playwright install chromium

      - name: Wait for JupyterLab
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http-get://localhost:8888/lab
          timeout: 360000

      - name: Execute integration tests
        working-directory: myextension
        run: |
          jlpm run playwright test ./ui-tests

      - name: Upload Playwright Test assets
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: myextension-playwright-test-assets
          path: |
            myextension/test-results

      - name: Upload Playwright Test report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: myextension-playwright-report
          path: |
            myextension/playwright-report
